// This file is auto-generated by @hey-api/openapi-ts

export const StatusUpdateSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        message: {
            type: 'string',
            nullable: true
        },
        source: {
            type: 'string',
            nullable: true
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            nullable: true,
            format: 'date-time'
        },
        analysis: {
            type: 'object',
            nullable: true,
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                model: {
                    type: 'string',
                    nullable: true
                },
                closures: {
                    type: 'array',
                    items: {
                        type: 'object',
                        properties: {
                            id: {
                                type: 'string',
                                format: 'uuid'
                            },
                            closureDate: {
                                type: 'string',
                                nullable: true,
                                format: 'date-time'
                            },
                            reopeningDate: {
                                type: 'string',
                                nullable: true,
                                format: 'date-time'
                            },
                            reasoning: {
                                type: 'string',
                                nullable: true
                            },
                            confidenceScore: {
                                type: 'integer',
                                nullable: true
                            },
                            flags: {
                                type: 'array',
                                items: {
                                    type: 'string'
                                }
                            }
                        },
                        required: [
                            'id',
                            'closureDate',
                            'reopeningDate',
                            'reasoning',
                            'confidenceScore',
                            'flags'
                        ]
                    }
                },
                createdAt: {
                    type: 'string',
                    format: 'date-time'
                },
                updatedAt: {
                    type: 'string',
                    nullable: true,
                    format: 'date-time'
                }
            },
            required: [
                'id',
                'model',
                'closures',
                'createdAt',
                'updatedAt'
            ]
        }
    },
    required: [
        'id',
        'message',
        'source',
        'createdAt',
        'updatedAt',
        'analysis'
    ],
    description: 'A Mt. Rainier pool status update.'
} as const;

export const NotifyEmailResultSchema = {
    type: 'object',
    properties: {
        poolUpdateId: {
            type: 'string',
            format: 'uuid'
        },
        analysisId: {
            type: 'string',
            format: 'uuid'
        },
        started: {
            type: 'integer'
        }
    },
    required: [
        'poolUpdateId',
        'analysisId',
        'started'
    ],
    description: 'Per-recipient email delivery outcomes.'
} as const;

export const NotifyEmailRequestSchema = {
    type: 'object',
    properties: {
        poolUpdateId: {
            type: 'string',
            format: 'uuid'
        }
    },
    required: [
        'poolUpdateId'
    ],
    description: 'Deliver the pool-closure email for a pool update\'s analysis.'
} as const;
