// This file is auto-generated by @hey-api/openapi-ts

export const StatusUpdateSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        message: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: [
        'id',
        'message',
        'source',
        'created_at',
        'updated_at'
    ],
    description: 'A Mt. Rainier pool status update.'
} as const;
