// This file is auto-generated by @hey-api/openapi-ts

export const StatusUpdateSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        message: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        poolClosureAnalysis: {
            type: 'object',
            nullable: true,
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                poolUpdateId: {
                    type: 'string',
                    format: 'uuid'
                },
                closureDate: {
                    type: 'string',
                    nullable: true,
                    format: 'date'
                },
                reopeningDate: {
                    type: 'string',
                    nullable: true,
                    format: 'date'
                },
                reasoning: {
                    type: 'string',
                    nullable: true
                },
                confidenceScore: {
                    type: 'integer',
                    nullable: true
                },
                createdAt: {
                    type: 'string',
                    format: 'date-time'
                },
                updatedAt: {
                    type: 'string',
                    nullable: true,
                    format: 'date-time'
                },
                flags: {
                    type: 'array',
                    items: {
                        type: 'string'
                    }
                }
            },
            required: [
                'id',
                'poolUpdateId',
                'closureDate',
                'reopeningDate',
                'reasoning',
                'confidenceScore',
                'createdAt',
                'updatedAt',
                'flags'
            ]
        }
    },
    required: [
        'id',
        'message',
        'source',
        'createdAt',
        'updatedAt',
        'poolClosureAnalysis'
    ],
    description: 'A Mt. Rainier pool status update.'
} as const;

export const NotifyEmailResultSchema = {
    type: 'object',
    properties: {
        poolUpdateId: {
            type: 'string',
            format: 'uuid'
        },
        analysisId: {
            type: 'string',
            format: 'uuid'
        },
        started: {
            type: 'integer'
        }
    },
    required: [
        'poolUpdateId',
        'analysisId',
        'started'
    ],
    description: 'Per-recipient email delivery outcomes.'
} as const;

export const NotifyEmailRequestSchema = {
    type: 'object',
    properties: {
        poolUpdateId: {
            type: 'string',
            format: 'uuid'
        }
    },
    required: [
        'poolUpdateId'
    ],
    description: 'Deliver the pool-closure email for a pool update\'s analysis.'
} as const;
