// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.ts';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.ts';
import { checkResponseTransformer } from './transformers.gen.ts';
import type { CheckData, CheckErrors, CheckResponses, NotifyEmailData, NotifyEmailErrors, NotifyEmailResponses } from './types.gen.ts';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new PoolClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class PoolClient extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<PoolClient> = new HeyApiRegistry<PoolClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        PoolClient.__registry.set(this, args?.key);
    }
    
    public check<ThrowOnError extends boolean = false>(options?: Options<CheckData, ThrowOnError>): RequestResult<CheckResponses, CheckErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<CheckResponses, CheckErrors, ThrowOnError>({
            responseTransformer: checkResponseTransformer,
            security: [{ name: 'apiKey', type: 'apiKey' }],
            url: '/api/check',
            ...options
        });
    }
    
    public notifyEmail<ThrowOnError extends boolean = false>(options: Options<NotifyEmailData, ThrowOnError>): RequestResult<NotifyEmailResponses, NotifyEmailErrors, ThrowOnError> {
        return (options.client ?? this.client).post<NotifyEmailResponses, NotifyEmailErrors, ThrowOnError>({
            security: [{ name: 'apiKey', type: 'apiKey' }],
            url: '/api/notify/email',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
