// This file is auto-generated by @hey-api/openapi-ts

import type { CheckResponse } from './types.gen.ts';

const statusUpdateSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    if (data.poolClosureAnalysis) {
        if (data.poolClosureAnalysis.closureDate) {
            data.poolClosureAnalysis.closureDate = new Date(data.poolClosureAnalysis.closureDate);
        }
        if (data.poolClosureAnalysis.reopeningDate) {
            data.poolClosureAnalysis.reopeningDate = new Date(data.poolClosureAnalysis.reopeningDate);
        }
        data.poolClosureAnalysis.createdAt = new Date(data.poolClosureAnalysis.createdAt);
        if (data.poolClosureAnalysis.updatedAt) {
            data.poolClosureAnalysis.updatedAt = new Date(data.poolClosureAnalysis.updatedAt);
        }
    }
    return data;
};

export const checkResponseTransformer = async (data: any): Promise<CheckResponse> => {
    if (data) {
        data = statusUpdateSchemaResponseTransformer(data);
    }
    return data;
};
