// This file is auto-generated by @hey-api/openapi-ts

import type { CheckResponse } from './types.gen.ts';

const statusUpdateSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const checkResponseTransformer = async (data: any): Promise<CheckResponse> => {
    if (data) {
        data = statusUpdateSchemaResponseTransformer(data);
    }
    return data;
};
