// This file is auto-generated by @hey-api/openapi-ts

import type { CheckResponse } from './types.gen.ts';

const statusUpdateSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    if (data.analysis) {
        data.analysis.closures = data.analysis.closures.map((item: any) => {
            if (item.closureDate) {
                item.closureDate = new Date(item.closureDate);
            }
            if (item.reopeningDate) {
                item.reopeningDate = new Date(item.reopeningDate);
            }
            return item;
        });
        data.analysis.createdAt = new Date(data.analysis.createdAt);
        if (data.analysis.updatedAt) {
            data.analysis.updatedAt = new Date(data.analysis.updatedAt);
        }
    }
    return data;
};

export const checkResponseTransformer = async (data: any): Promise<CheckResponse> => {
    if (data) {
        data = statusUpdateSchemaResponseTransformer(data);
    }
    return data;
};
