// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * A Mt. Rainier pool status update.
 */
export type StatusUpdate = {
    id: string;
    message: string | null;
    source: string | null;
    createdAt: Date;
    updatedAt: Date | null;
    analysis: {
        id: string;
        model: string | null;
        closures: Array<{
            id: string;
            closureDate: Date | null;
            reopeningDate: Date | null;
            reasoning: string | null;
            confidenceScore: number | null;
            flags: Array<string>;
        }>;
        createdAt: Date;
        updatedAt: Date | null;
    } | null;
};

/**
 * Per-recipient email delivery outcomes.
 */
export type NotifyEmailResult = {
    analysisId: string;
    started: number;
};

/**
 * Deliver the pool-closure email for a pool operator analysis.
 */
export type NotifyEmailRequest = {
    analysisId: string;
};

export type CheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/check';
};

export type CheckErrors = {
    /**
     * Internal server error.
     */
    500: string;
};

export type CheckError = CheckErrors[keyof CheckErrors];

export type CheckResponses = {
    /**
     * Found a pool status update.
     */
    200: StatusUpdate;
    /**
     * No status update available.
     */
    204: void;
};

export type CheckResponse = CheckResponses[keyof CheckResponses];

export type NotifyEmailData = {
    body: NotifyEmailRequest;
    path?: never;
    query?: never;
    url: '/api/notify/email';
};

export type NotifyEmailErrors = {
    /**
     * No analysis exists for the given id.
     */
    404: string;
    /**
     * Internal server error.
     */
    500: string;
};

export type NotifyEmailError = NotifyEmailErrors[keyof NotifyEmailErrors];

export type NotifyEmailResponses = {
    /**
     * Delivery attempted; returns per-recipient outcomes.
     */
    200: NotifyEmailResult;
};

export type NotifyEmailResponse = NotifyEmailResponses[keyof NotifyEmailResponses];
