// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/check';
};

export type CheckErrors = {
    /**
     * Internal server error.
     */
    500: string;
};

export type CheckError = CheckErrors[keyof CheckErrors];

export type CheckResponses = {
    /**
     * Finished getting pool status.
     */
    200: string;
};

export type CheckResponse = CheckResponses[keyof CheckResponses];
