// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * A Mt. Rainier pool status update.
 */
export type StatusUpdate = {
    id: string;
    message: string;
    source: string;
    created_at: Date;
    updated_at: Date;
};

export type CheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/check';
};

export type CheckErrors = {
    /**
     * Internal server error.
     */
    500: string;
};

export type CheckError = CheckErrors[keyof CheckErrors];

export type CheckResponses = {
    /**
     * Found a pool status update.
     */
    200: StatusUpdate;
    /**
     * No status update available.
     */
    204: void;
};

export type CheckResponse = CheckResponses[keyof CheckResponses];
